server:
  port: 8090
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/java225?useUnicode=true&useSSL=false&characterEncoding=utf8
      min-idle: 1
      max-active: 10
      initial-size: 1
      max-wait: 60000
      validation-query: select 1