server:
  port: 8090
  servlet:
    context-path: /
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.acrel.demo.entity.*
  configuration.map-underscore-to-camel-case: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.112.230:3306/java225?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 300000
      filters: stat,wall
      stat-view-servlet:
        login-username: root
        login-password: 123654